# Generated by Django 4.1.4 on 2022-12-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillcatogary',
            old_name='catogary',
            new_name='categary',
        ),
    ]
