# Generated by Django 4.1.4 on 2022-12-22 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill', '0002_rename_catogary_skillcatogary_categary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skillcatogary',
            old_name='categary',
            new_name='category',
        ),
    ]
