# Generated by Django 4.1.4 on 2022-12-25 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skill', '0003_rename_categary_skillcatogary_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmatrix',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.skilllevel'),
        ),
        migrations.AlterField(
            model_name='skillmatrix',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skill.skills'),
        ),
        migrations.AlterField(
            model_name='skillmatrix',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
